### ISSUE TITLE
Feed back on week3 homework 

### ISSUE THREAD

**Issue by AllouhM** [ThreePalmTrees/hyf-html-css#1]
Hello Husam, it seems to me based on my limited experience a very good work especially for this homework as it was a challenge for most of us. However,  I have some minor notes.
Unneeded empty element <li>, for the last section, I could not figure out why you used <h3> outside the section. Otherwise, your HTML is very neat.  Also, your CSS is quite good. Good work and keep it up.

**Comment by ThreePalmTrees** [comment]
Thanks for your feedback Mahmoud,
for the h3 I didn't want to group the heading with the list items for styling purposes, and couldn't think of a better way to do it :)
